{% set version = "0.36.0" %}

package:
  name: jedi-language-server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jedi-language-server/jedi-language-server-{{ version }}.tar.gz
  sha256: 30f69eab674ed6b7e35316ea558d2bdd150f1b05ce7a9f65dd67388ef1fa0e35

build:
  number: 0
  noarch: python
  entry_points:
    - jedi-language-server = jedi_language_server.cli:cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - poetry >=1.0.5
    - python >=3.7
  run:
    - docstring-to-markdown >=0.4,<1.0
    - importlib-metadata >=3.10.0,<4
    - jedi >=0.18.0,<0.19.0
    - pydantic >=1.7,<2.0
    - pygls >=0.11.1,<0.12.0
    - python >=3.7

test:
  imports:
    - jedi_language_server
  commands:
    - pip check
    - jedi-language-server --version
    - jedi-language-server --help
  requires:
    - pip

about:
  home: https://github.com/pappasam/jedi-language-server
  summary: A language server for Jedi!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
